/* Liverpool Blue Bottle — V3.24 stable catalogue + page-level specials campaign */
window.LBB_SPECIALS_CAMPAIGN = {
  enabled: true,
  campaignStart: "2026-09-01",
  campaignEnd: "2026-09-15",
  label: "1 September – 15 September 2026"
};

window.LBB_CATALOG = [
  {
    "id": "4th-street-natural-sweet-red-5l",
    "name": "4th Street Natural Sweet Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "4th-street-natural-sweet-red-5l.png"
  },
  {
    "id": "4th-street-natural-sweet-ros-5l",
    "name": "4th Street Natural Sweet Rosé 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "4th-street-natural-sweet-rose-5l.png"
  },
  {
    "id": "4th-street-natural-sweet-white-5l",
    "name": "4th Street Natural Sweet White 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "4th-street-natural-sweet-white-5l.png"
  },
  {
    "id": "4th-street-sweet-late-harvest-5l",
    "name": "4th Street Sweet Late Harvest 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "4th-street-sweet-late-harvest-5l.png"
  },
  {
    "id": "ballantine-s",
    "name": "Ballantine’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "BS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "ballantines-finest.png"
  },
  {
    "id": "bell-s",
    "name": "Bell’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 229.99,
    "initial": "BS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "bells.png"
  },
  {
    "id": "black-white",
    "name": "Black & White",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 209.99,
    "initial": "BW",
    "specialPrice": 189.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-black-white.png"
  },
  {
    "id": "chivas-regal-12yr",
    "name": "Chivas Regal 12yr",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 349.0,
    "initial": "CR1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "chivas-regal-12yr.png"
  },
  {
    "id": "crabbie-s-yardhead",
    "name": "Crabbie’s Yardhead",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 269.99,
    "initial": "CSY",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "crabbies-yardhead.png"
  },
  {
    "id": "firstwatch",
    "name": "Firstwatch",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 199.0,
    "initial": "F",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-firstwatch.png"
  },
  {
    "id": "gentleman-jack",
    "name": "Gentleman Jack",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 399.99,
    "initial": "GJ",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-gentleman-jack.png"
  },
  {
    "id": "grant-s",
    "name": "Grant’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "GS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-grants.png"
  },
  {
    "id": "harrier",
    "name": "Harrier",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 179.0,
    "initial": "H",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-harrier.png"
  },
  {
    "id": "harrier-1l",
    "name": "Harrier 1L",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "1L",
    "normalPrice": 219.99,
    "initial": "H1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-harrier-1l.png"
  },
  {
    "id": "j-b-rare",
    "name": "J&B Rare",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 229.99,
    "initial": "J&B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-jb-rare.png"
  },
  {
    "id": "jack-daniel-s",
    "name": "Jack Daniel's",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 315,
    "initial": "JD",
    "specialPrice": 299.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-jack-daniels.png"
  },
  {
    "id": "jack-daniel-s-tennessee-honey",
    "name": "Jack Daniel's Tennessee Honey",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 315,
    "initial": "JD H",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-jack-honey.png"
  },
  {
    "id": "jack-daniel-s-tennessee-apple",
    "name": "Jack Daniel's Tennessee Apple",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 315,
    "initial": "JD A",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-jack-apple.png"
  },
  {
    "id": "jameson",
    "name": "Jameson",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 369.99,
    "initial": "J",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "jameson.png"
  },
  {
    "id": "jameson-select-reserve",
    "name": "Jameson Select Reserve",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 549.0,
    "initial": "JSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "jameson-select-reserve.png"
  },
  {
    "id": "johnnie-walker-black-label",
    "name": "Johnnie Walker Black Label",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 429.99,
    "initial": "JWB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "johnnie-walker-black-label.png"
  },
  {
    "id": "johnnie-walker-red-label",
    "name": "Johnnie Walker Red Label",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 299.99,
    "initial": "JWR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "johnnie-walker-red-label.png"
  },
  {
    "id": "peaky-blinders",
    "name": "Peaky Blinders Irish Whiskey",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "700ml",
    "normalPrice": 259.99,
    "initial": "PB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "peaky-blinders.png"
  },
  {
    "id": "samuel-gelston-s-irish-whisky",
    "name": "Samuel Gelston’s Irish Whiskey",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 279.99,
    "initial": "SGS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "samuel-gelston-s-irish-whisky.png"
  },
  {
    "id": "the-famous-grouse",
    "name": "The Famous Grouse",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 269.0,
    "initial": "TFG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "the-famous-grouse.png"
  },
  {
    "id": "the-pogues",
    "name": "The Pogues Triple Distilled Irish Whiskey",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "700ml",
    "normalPrice": 289.99,
    "initial": "TP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "the-pogues.png"
  },
  {
    "id": "the-quiet-man",
    "name": "The Quiet Man Superior Irish Whiskey Blend",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 289.0,
    "initial": "TQM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "the-quiet-man.png"
  },
  {
    "id": "three-ships-bourbon-cask",
    "name": "Three Ships Premium Whisky Bourbon Cask",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 294.99,
    "initial": "TSB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "three-ships-bourbon-cask.png"
  },
  {
    "id": "tullamore-dew",
    "name": "Tullamore D.E.W. Irish Whiskey",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 335.0,
    "initial": "TD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "tullamore-dew.png"
  },
  {
    "id": "vat-69",
    "name": "Vat 69",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 185.0,
    "initial": "V6",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "vat-69.png"
  },
  {
    "id": "buffelsfontein",
    "name": "Buffelsfontein",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "buffelsfontein.png"
  },
  {
    "id": "commando",
    "name": "Commando",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 199.0,
    "initial": "C",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "commando.png"
  },
  {
    "id": "flight-of-the-fish-eagle",
    "name": "Fish Eagle",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 209.99,
    "initial": "FOT",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "klipdrift-export",
    "name": "Klipdrift Export",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 205.0,
    "initial": "KE",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-klipdrift-export.png"
  },
  {
    "id": "klipdrift-premium",
    "name": "Klipdrift Premium",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "KP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-klipdrift-premium.png"
  },
  {
    "id": "olof-bergh",
    "name": "Olof Bergh",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 179.99,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "olof-bergh.png"
  },
  {
    "id": "kwv-10-year-old",
    "name": "KWV 10 year old",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 299.99,
    "initial": "K10",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "kwv-10-year-old.png"
  },
  {
    "id": "kwv-5-year-old",
    "name": "KWV 5 year old",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "K5",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "kwv-5-year-old.png"
  },
  {
    "id": "red-heart-rum",
    "name": "Red Heart Rum",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "RHR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "red-heart-rum.png"
  },
  {
    "id": "captain-morgan-spiced-gold",
    "name": "Captain Morgan Spiced Gold",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "CMS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "captain-morgan-spiced-gold.png"
  },
  {
    "id": "dead-man-s-fingers-dark",
    "name": "Dead Man’s Fingers Dark",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "DMF",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "dead-mans-fingers-dark.png"
  },
  {
    "id": "dead-man-s-fingers-spiced",
    "name": "Dead Man’s Fingers Spiced",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "DMFS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "dead-mans-fingers-spiced.png"
  },
  {
    "id": "c-roc-snap-frost",
    "name": "Cîroc Snap Frost",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 539.99,
    "initial": "CSF",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "c-roc-snap-frost.png"
  },
  {
    "id": "c-roc-summer",
    "name": "Cîroc Summer",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "CS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "c-roc-summer.png"
  },
  {
    "id": "red-square",
    "name": "Red Square",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 155.0,
    "initial": "RS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "red-square.png"
  },
  {
    "id": "red-square-energy-infusion",
    "name": "Red Square Energy Infusion",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 135.0,
    "initial": "RSE",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "red-square-energy-infusion.png"
  },
  {
    "id": "russian-bear",
    "name": "Russian Bear",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "RB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "russian-bear.png"
  },
  {
    "id": "cazadores-a-ejo",
    "name": "Cazadores Añejo",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 259.99,
    "initial": "CA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "cazadores-anejo.png"
  },
  {
    "id": "don-julio-blanco",
    "name": "Don Julio Blanco",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 850.0,
    "initial": "DJB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "don-julio-blanco.png"
  },
  {
    "id": "don-julio-reposado",
    "name": "Don Julio Reposado",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 1299.99,
    "initial": "DJR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-don-julio-reposado.png"
  },
  {
    "id": "el-jimador-reposado",
    "name": "El Jimador Reposado",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 355.0,
    "initial": "EJR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "el-jimador-reposado.png"
  },
  {
    "id": "jose-cuervo-especial-silver",
    "name": "Jose Cuervo Especial Silver",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 285.0,
    "initial": "JCES",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "jose-cuervo-especial-silver.png"
  },
  {
    "id": "another-hendrick-s",
    "name": "Hendrick’s Another",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "HA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "another-hendrick-s.png"
  },
  {
    "id": "belgravia",
    "name": "Belgravia",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "belgravia.png"
  },
  {
    "id": "belgravia-platinum",
    "name": "Belgravia Platinum",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 179.99,
    "initial": "BP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "belgravia-platinum.png"
  },
  {
    "id": "gordon-s",
    "name": "Gordon’s",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 189.0,
    "initial": "G",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "gordon-s.png"
  },
  {
    "id": "hendrick-s-gin-original",
    "name": "Hendrick’s Gin Original",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "HGO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "hendrick-s-gin-original.png"
  },
  {
    "id": "african-secret-marula",
    "name": "African Secret Marula Cream",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "ASM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "african-secret-marula.png"
  },
  {
    "id": "amarula",
    "name": "Amarula Cream",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "AC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "amarula-cream.png"
  },
  {
    "id": "amarula-1l",
    "name": "Amarula 1L",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "1L",
    "normalPrice": 215.0,
    "initial": "A1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "amarula-cream-1l.png"
  },
  {
    "id": "coco-rico-salted-caramel-coconut-cream",
    "name": "Coco Rico Salted Caramel & Coconut Cream",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "CRC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-coco-rico.png"
  },
  {
    "id": "el-bravo-strawberry",
    "name": "El Bravo Strawberry",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "EBS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "el-bravo-strawberry.png"
  },
  {
    "id": "strawberry-lips",
    "name": "Strawberry Lips",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "SL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "strawberry-lips.png"
  },
  {
    "id": "sidekick-strawberry-cream",
    "name": "Sidekick Strawberry & Cream",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 115.0,
    "initial": "SSC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "sidekick-strawberry-cream.png"
  },
  {
    "id": "sidekick-cookies-cream",
    "name": "Sidekick Cookies & Cream",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 115.0,
    "initial": "SCC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "sidekick-cookies-cream.png"
  },
  {
    "id": "jagermeister-classic",
    "name": "Jägermeister (Classic)",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 329.99,
    "initial": "JAG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "jagermeister-classic.jpg"
  },
  {
    "id": "jagermeister-manifest",
    "name": "Jägermeister Manifest",
    "category": "Liqueurs / Cream Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "1000ml",
    "normalPrice": 449.0,
    "initial": "JGM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "jagermeister-manifest.jpg"
  },
  {
    "id": "southern-comfort-original",
    "name": "Southern Comfort Original",
    "category": "Whiskey Liqueurs",
    "categoryId": "whiskey-liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "SCO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "southern-comfort-original.png"
  },
  {
    "id": "southern-comfort-lime",
    "name": "Southern Comfort Lime",
    "category": "Whiskey Liqueurs",
    "categoryId": "whiskey-liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 155.0,
    "initial": "SCL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "southern-comfort-lime.png"
  },
  {
    "id": "veuve-clicquot-brut",
    "name": "Veuve Clicquot Brut",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 749.99,
    "initial": "VCB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "veuve-clicquot-brut.png"
  },
  {
    "id": "veuve-clicquot-rose",
    "name": "Veuve Clicquot Rosé",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 949.0,
    "initial": "VCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "veuve-clicquot-rose.png"
  },
  {
    "id": "veuve-clicquot-rich",
    "name": "Veuve Clicquot Rich",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 1049.0,
    "initial": "VCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "veuve-clicquot-rich.png"
  },
  {
    "id": "moet-chandon-imperial-brut",
    "name": "Moët & Chandon Impérial Brut",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 649.0,
    "initial": "MCB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "moet-chandon-imperial-brut.png"
  },
  {
    "id": "moet-chandon-ice-imperial",
    "name": "Moët & Chandon Ice Impérial",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 879.0,
    "initial": "MCI",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "moet-chandon-ice-imperial.png"
  },
  {
    "id": "moet-chandon-nectar-imperial",
    "name": "Moët & Chandon Nectar Impérial",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 799.0,
    "initial": "MCN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "moet-chandon-nectar-imperial.png"
  },
  {
    "id": "jc-le-roux-le-domaine",
    "name": "J.C. Le Roux Le Domaine",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-la-fleurette",
    "name": "J.C. Le Roux La Fleurette",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLF",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-la-chanson",
    "name": "J.C. Le Roux La Chanson",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-le-domaine-non-alcoholic",
    "name": "J.C. Le Roux Le Domaine Non-Alcoholic",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 90.0,
    "initial": "JLD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hennessy-vs",
    "name": "Hennessy VS",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 580.0,
    "initial": "HVS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "hennessy-vs.png"
  },
  {
    "id": "martell-vs",
    "name": "Martell VS",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 499.0,
    "initial": "MVS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "martell-vs.png"
  },
  {
    "id": "r-my-martin-vsop",
    "name": "Rémy Martin VSOP",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 989.99,
    "initial": "RMV",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "remy-martin-vsop.png"
  },
  {
    "id": "honor-extra-cognac-gold-filtered",
    "name": "Honor Extra Cognac Gold Filtered",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 539.0,
    "initial": "HEC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "honor-extra-cognac.png"
  },
  {
    "id": "hennessy-vsop",
    "name": "Hennessy VSOP",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 899.99,
    "initial": "HVSOP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "hennessy-vsop.png"
  },
  {
    "id": "belgravia-gin-dry-lemon",
    "name": "Belgravia Gin & Dry Lemon",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 129.99,
    "initial": "BGD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-belgravia-gin-dry-lemon.png"
  },
  {
    "id": "brutal-fruit-ruby-apple",
    "name": "Brutal Fruit Ruby Apple",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 125.0,
    "initial": "BFR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-brutal-fruit-ruby-apple.png"
  },
  {
    "id": "carling-black-label",
    "name": "Carling Black Label",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CBL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-carling-black-label.png"
  },
  {
    "id": "castle-lager",
    "name": "Castle Lager",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 95.0,
    "initial": "CL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-castle-lager.png"
  },
  {
    "id": "castle-lite",
    "name": "Castle Lite",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CLT",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "special-castle-lite.png"
  },
  {
    "id": "robertson-mimosa-orange-spritzer",
    "name": "Robertson Mimosa Orange Spritzer",
    "category": "Ready-To-Drink",
    "categoryId": "ready-to-drink",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 80.0,
    "initial": "MO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "sedgwick-s-the-original-old-brown",
    "name": "Sedgwick's The Original Old Brown",
    "category": "Fortified Wine",
    "categoryId": "fortified-wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 54.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "orC-full-cream-fortified-wine",
    "name": "ORC Full Cream Fortified Wine",
    "category": "Fortified Wine",
    "categoryId": "fortified-wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 95.0,
    "initial": "ORC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-chapel-red-1-5l",
    "name": "Robertson Chapel Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-red-1.5l.jpg"
  },
  {
    "id": "robertson-chapel-natural-sweet-red-1-5l",
    "name": "Robertson Chapel Natural Sweet Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-sweet-red-1.5l.jpg"
  },
  {
    "id": "romantic-lips-sweet-red-5l",
    "name": "Romantic Lips Sweet Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-dry-red-5l",
    "name": "Romantic Lips Dry Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-sweet-white-5l",
    "name": "Romantic Lips Sweet White 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-sweet-rose-5l",
    "name": "Romantic Lips Sweet Rosé 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-dry-red-5l",
    "name": "Rusthof Dry Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-natural-sweet-red-5l",
    "name": "Rusthof Natural Sweet Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RNSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-natural-rose-5l",
    "name": "Rusthof Natural Rosé 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RNR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-classic-special-red",
    "name": "1659 Classic Special Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "CSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-rose",
    "name": "1659 Rosé",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "R",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-sweet-red",
    "name": "1659 Sweet Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "SR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-adelpracht-late-harvest-1l",
    "name": "Drostdy-Hof Adelpracht Late Harvest 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 49.0,
    "initial": "DAL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-adelpracht-late-harvest-5l",
    "name": "Drostdy-Hof Adelpracht Late Harvest 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 185.0,
    "initial": "DAL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-claret-select-750ml",
    "name": "Drostdy-Hof Claret Select 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 58.0,
    "initial": "DCS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-claret-select-5l",
    "name": "Drostdy-Hof Claret Select 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 185.0,
    "initial": "DCS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-natural-sweet-white-750ml",
    "name": "Robertson Natural Sweet White 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 59.99,
    "initial": "RNSW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-dry-1l",
    "name": "Robertson Dry 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-crisp-dry-white-1l",
    "name": "Robertson Crisp Dry White 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RCDW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-natural-sweet-rose-1l",
    "name": "Robertson Natural Sweet Rosé 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RNSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "graca-rose-750ml",
    "name": "Graça Rosé 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 65.0,
    "initial": "GR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "lutzville-vineyards-pinotage-750ml",
    "name": "Lutzville Vineyards Pinotage 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "LVP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tassenberg",
    "name": "Tassenberg",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 45.0,
    "initial": "T",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "nederburg-baronne",
    "name": "Nederburg Baronne",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.0,
    "initial": "NB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "spier-merlot",
    "name": "Spier Merlot",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.99,
    "initial": "SM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "spier-sauvignon-blanc",
    "name": "Spier Sauvignon Blanc",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.99,
    "initial": "SSB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "two-oceans-cabernet-sauvignon-merlot",
    "name": "Two Oceans Cabernet Sauvignon Merlot",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 69.99,
    "initial": "TOC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "two-oceans-sauvignon-blanc",
    "name": "Two Oceans Sauvignon Blanc",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 69.99,
    "initial": "TOS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-medium-sweet-red",
    "name": "Versailles Medium Sweet Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VMSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-dry-red",
    "name": "Versailles Dry Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-sweet-red-5l",
    "name": "Romantic Lips Sweet Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-dry-red-5l",
    "name": "Romantic Lips Dry Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-sweet-white-5l",
    "name": "Romantic Lips Sweet White 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "romantic-lips-sweet-rose-5l",
    "name": "Romantic Lips Sweet Rosé 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 130.0,
    "initial": "RLSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-dry-red-5l",
    "name": "Rusthof Dry Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-natural-sweet-red-5l",
    "name": "Rusthof Natural Sweet Red 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RNSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "rusthof-natural-rose-5l",
    "name": "Rusthof Natural Rosé 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 160.0,
    "initial": "RNR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-classic-special-red",
    "name": "1659 Classic Special Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "CSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-rose",
    "name": "1659 Rosé",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "R",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "1659-sweet-red",
    "name": "1659 Sweet Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "SR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-chapel-red-1-5l",
    "name": "Robertson Chapel Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-red-1.5l.jpg"
  },
  {
    "id": "robertson-chapel-natural-sweet-red-1-5l",
    "name": "Robertson Chapel Natural Sweet Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-sweet-red-1.5l.jpg"
  },
  {
    "id": "drostdy-hof-adelpracht-late-harvest-1l",
    "name": "Drostdy-Hof Adelpracht Late Harvest 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 49.0,
    "initial": "DAL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-adelpracht-late-harvest-5l",
    "name": "Drostdy-Hof Adelpracht Late Harvest 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 185.0,
    "initial": "DAL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-claret-select-750ml",
    "name": "Drostdy-Hof Claret Select 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 58.0,
    "initial": "DCS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "drostdy-hof-claret-select-5l",
    "name": "Drostdy-Hof Claret Select 5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 185.0,
    "initial": "DCS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-natural-sweet-white-750ml",
    "name": "Robertson Natural Sweet White 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 59.99,
    "initial": "RNSW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-dry-1l",
    "name": "Robertson Dry 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-crisp-dry-white-1l",
    "name": "Robertson Crisp Dry White 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RCDW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-natural-sweet-rose-1l",
    "name": "Robertson Natural Sweet Rosé 1L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1L",
    "normalPrice": 50.0,
    "initial": "RNSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "graca-rose-750ml",
    "name": "Graça Rosé 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 65.0,
    "initial": "GR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "lutzville-vineyards-pinotage-750ml",
    "name": "Lutzville Vineyards Pinotage 750ml",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 50.0,
    "initial": "LVP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tassenberg",
    "name": "Tassenberg",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 45.0,
    "initial": "T",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "nederburg-baronne",
    "name": "Nederburg Baronne",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.0,
    "initial": "NB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "spier-merlot",
    "name": "Spier Merlot",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.99,
    "initial": "SM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "spier-sauvignon-blanc",
    "name": "Spier Sauvignon Blanc",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 89.99,
    "initial": "SSB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "two-oceans-cabernet-sauvignon-merlot",
    "name": "Two Oceans Cabernet Sauvignon Merlot",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 69.99,
    "initial": "TOC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "two-oceans-sauvignon-blanc",
    "name": "Two Oceans Sauvignon Blanc",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 69.99,
    "initial": "TOS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-medium-sweet-red",
    "name": "Versailles Medium Sweet Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VMSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-dry-red",
    "name": "Versailles Dry Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "orC-full-cream-fortified-wine",
    "name": "ORC Full Cream Fortified Wine",
    "category": "Fortified Wine",
    "categoryId": "fortified-wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 95.0,
    "initial": "ORC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-dry-red",
    "name": "Versailles Dry Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VDR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "versailles-medium-sweet-red",
    "name": "Versailles Medium Sweet Red",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 40.0,
    "initial": "VMSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-chapel-red-1-5l",
    "name": "Robertson Chapel Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-red-1.5l.jpg"
  },
  {
    "id": "robertson-chapel-natural-sweet-red-1-5l",
    "name": "Robertson Chapel Natural Sweet Red 1.5L",
    "category": "Wines",
    "categoryId": "wine",
    "emoji": "🍷",
    "size": "1.5L",
    "normalPrice": 99.0,
    "initial": "RCN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": "robertson-chapel-sweet-red-1.5l.jpg"
  },
  {
    "id": "jc-le-roux-le-domaine",
    "name": "J.C. Le Roux Le Domaine",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-la-fleurette",
    "name": "J.C. Le Roux La Fleurette",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLF",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-la-chanson",
    "name": "J.C. Le Roux La Chanson",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 99.99,
    "initial": "JLC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jc-le-roux-le-domaine-non-alcoholic",
    "name": "J.C. Le Roux Le Domaine Non-Alcoholic",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 90.0,
    "initial": "JLD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "sedgwick-s-the-original-old-brown",
    "name": "Sedgwick's The Original Old Brown",
    "category": "Fortified Wine",
    "categoryId": "fortified-wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 54.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "orC-full-cream-fortified-wine",
    "name": "ORC Full Cream Fortified Wine",
    "category": "Fortified Wine",
    "categoryId": "fortified-wine",
    "emoji": "🍷",
    "size": "750ml",
    "normalPrice": 95.0,
    "initial": "ORC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  }
];
