/* Liverpool Blue Bottle — V3.24 stable catalogue + page-level specials campaign */
window.LBB_SPECIALS_CAMPAIGN = {
  enabled: true,
  campaignStart: "2026-09-01",
  campaignEnd: "2026-09-15",
  label: "1 September – 15 September 2026"
};

window.LBB_CATALOG = [
  {
    "id": "4th-street-natural-sweet-red-5l",
    "name": "4th Street Natural Sweet Red 5L",
    "category": "Wines (4th Street 5L)",
    "categoryId": "wine-5l",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "4th-street-natural-sweet-ros-5l",
    "name": "4th Street Natural Sweet Rosé 5L",
    "category": "Wines (4th Street 5L)",
    "categoryId": "wine-5l",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "4th-street-natural-sweet-white-5l",
    "name": "4th Street Natural Sweet White 5L",
    "category": "Wines (4th Street 5L)",
    "categoryId": "wine-5l",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SN",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "4th-street-sweet-late-harvest-5l",
    "name": "4th Street Sweet Late Harvest 5L",
    "category": "Wines (4th Street 5L)",
    "categoryId": "wine-5l",
    "emoji": "🍷",
    "size": "5L",
    "normalPrice": 165.0,
    "initial": "4SS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "ballantine-s",
    "name": "Ballantine’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "BS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "bell-s",
    "name": "Bell’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 229.99,
    "initial": "BS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "black-white",
    "name": "Black & White",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 209.99,
    "initial": "BW",
    "specialPrice": 189.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/black-white.jpg"
  },
  {
    "id": "chivas-regal-12yr",
    "name": "Chivas Regal 12yr",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 349.0,
    "initial": "CR1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "crabbie-s-yardhead",
    "name": "Crabbie’s Yardhead",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 269.99,
    "initial": "CSY",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "firstwatch",
    "name": "Firstwatch",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 199.0,
    "initial": "F",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "gentleman-jack",
    "name": "Gentleman Jack",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 399.99,
    "initial": "GJ",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "grant-s",
    "name": "Grant’s",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "GS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "harrier",
    "name": "Harrier",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 179.0,
    "initial": "H",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "harrier-1l",
    "name": "Harrier 1L",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "1L",
    "normalPrice": 219.99,
    "initial": "H1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "j-b-rare",
    "name": "J&B Rare",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 229.99,
    "initial": "J&B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jack-daniel-s",
    "name": "Jack Daniel's",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 315,
    "initial": "JD",
    "specialPrice": 299.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/jack-daniel-s.jpg"
  },
  {
    "id": "jameson",
    "name": "Jameson",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 369.99,
    "initial": "J",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jameson-select-reserve",
    "name": "Jameson Select Reserve",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 549.0,
    "initial": "JSR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "johnnie-walker-black-label",
    "name": "Johnnie Walker Black Label",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 429.99,
    "initial": "JWB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "johnnie-walker-red-label",
    "name": "Johnnie Walker Red Label",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 299.99,
    "initial": "JWR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "peaky-blinders",
    "name": "Peaky Blinders",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 259.99,
    "initial": "PB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "samuel-gelston-s-irish-whisky",
    "name": "Samuel Gelston’s Irish Whisky",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 279.99,
    "initial": "SGS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "the-famous-grouse",
    "name": "The Famous Grouse",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 269.0,
    "initial": "TFG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "the-pogues",
    "name": "The Pogues",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 289.99,
    "initial": "TP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "the-quiet-man",
    "name": "The Quiet Man",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 289.0,
    "initial": "TQM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "three-ships-bourbon-cask",
    "name": "Three Ships Bourbon Cask",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 294.99,
    "initial": "TSB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tullamore-dew",
    "name": "Tullamore Dew",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 335.0,
    "initial": "TD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "vat-69",
    "name": "Vat 69",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 185.0,
    "initial": "V6",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "buffelsfontein",
    "name": "Buffelsfontein",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "commando",
    "name": "Commando",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 199.0,
    "initial": "C",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "flight-of-the-fish-eagle",
    "name": "Flight of the Fish Eagle",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 209.99,
    "initial": "FOT",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "klipdrift-export",
    "name": "Klipdrift Export",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 205,
    "initial": "KE",
    "specialPrice": 185,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/klipdrift-export.jpg"
  },
  {
    "id": "klipdrift-premium",
    "name": "Klipdrift Premium",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 239.99,
    "initial": "KP",
    "specialPrice": 219.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/klipdrift-premium.jpg"
  },
  {
    "id": "kwv-10-year-old",
    "name": "KWV 10 Year Old",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 409.99,
    "initial": "K1Y",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "kwv-3-year-old",
    "name": "KWV 3 Year Old",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 195.0,
    "initial": "K3Y",
    "specialPrice": 179.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/kwv-3-year-old.jpg"
  },
  {
    "id": "kwv-5-year-old",
    "name": "KWV 5 Year Old",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 225.0,
    "initial": "K5Y",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "kwv-vs-pot-still",
    "name": "KWV VS Pot Still",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 349.99,
    "initial": "KVP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "olof-bergh",
    "name": "Olof Bergh",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "richelieu",
    "name": "Richelieu International",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "R",
    "specialPrice": 199.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/richelieu-international.jpg"
  },
  {
    "id": "viceroy",
    "name": "Viceroy",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "V",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "wellington",
    "name": "Wellington",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 180.0,
    "initial": "W",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "wellington-1l",
    "name": "Wellington 1L",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "1L",
    "normalPrice": 240.0,
    "initial": "W1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "captain-morgan-spiced-gold",
    "name": "Captain Morgan Spiced Gold",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "CM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "dead-man-s-fingers-dark",
    "name": "Dead Man’s Fingers Dark",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "DMS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "dead-man-s-fingers-spiced",
    "name": "Dead Man’s Fingers Spiced",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "DMS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "red-heart-rum",
    "name": "Red Heart Rum",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "RH",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "c-roc-snap-frost",
    "name": "Cîroc Snap Frost",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 539.99,
    "initial": "CRS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "c-roc-summer",
    "name": "Cîroc Summer",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "CRS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "red-square",
    "name": "Red Square",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 155.0,
    "initial": "RS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "red-square-energy-infusion",
    "name": "Red Square Energy Infusion",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 135.0,
    "initial": "RSE",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "russian-bear",
    "name": "Russian Bear",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "RB",
    "specialPrice": 149.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/russian-bear.jpg"
  },
  {
    "id": "russian-bear-1l",
    "name": "Russian Bear 1L",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "1L",
    "normalPrice": 220.0,
    "initial": "RB1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "russian-bear-pineapple",
    "name": "Russian Bear Pineapple",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "RBP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "russian-bear-wild-berry",
    "name": "Russian Bear Wild Berry",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "RBW",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "skyy",
    "name": "Skyy",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 269.0,
    "initial": "S",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "smirnoff",
    "name": "Smirnoff",
    "category": "Vodka",
    "categoryId": "vodka",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 170.0,
    "initial": "S",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "cazadores-a-ejo",
    "name": "Cazadores Añejo",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 259.99,
    "initial": "CAE",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "don-julio-blanco",
    "name": "Don Julio Blanco",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 850.0,
    "initial": "DJB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "don-julio-reposado",
    "name": "Don Julio Reposado Tequila",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 1299.99,
    "initial": "DJR",
    "specialPrice": 799.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/don-julio-reposado-tequila.jpg"
  },
  {
    "id": "el-jimador-reposado",
    "name": "El Jimador Reposado",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 355.0,
    "initial": "EJR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jos-cuervo",
    "name": "José Cuervo",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 285.0,
    "initial": "JC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "olmeca-reposado",
    "name": "Olmeca Reposado",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 289.99,
    "initial": "OR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "olmeca-silver",
    "name": "Olmeca Silver",
    "category": "Tequila",
    "categoryId": "tequila",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 289.99,
    "initial": "OS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "another-hendrick-s",
    "name": "Hendrick’s Another",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "AHS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "belgravia",
    "name": "Belgravia",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "belgravia-platinum",
    "name": "Belgravia Platinum",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 179.99,
    "initial": "BP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "gordon-s",
    "name": "Gordon’s",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 189.0,
    "initial": "GS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hendrick-s-gin-original",
    "name": "Hendrick’s Gin Original",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "HSG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "inverroche-amber",
    "name": "Inverroche Amber",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 489.99,
    "initial": "IA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "inverroche-classic",
    "name": "Inverroche Classic",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 489.99,
    "initial": "IC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "inverroche-verdant",
    "name": "Inverroche Verdant",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 489.99,
    "initial": "IV",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "old-buck",
    "name": "Old Buck",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 170.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "strettons-original",
    "name": "Strettons Original",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 179.99,
    "initial": "SO",
    "specialPrice": 149.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/strettons-original.jpg"
  },
  {
    "id": "tanqueray-blackcurrant",
    "name": "Tanqueray Blackcurrant",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 325.0,
    "initial": "TB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tanqueray-flor-de-sevilla",
    "name": "Tanqueray Flor de Sevilla",
    "category": "Gin",
    "categoryId": "gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 325.0,
    "initial": "TFD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "african-secret-marula",
    "name": "African Secret Marula",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "ASM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "amarula",
    "name": "Amarula Cream",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "A",
    "specialPrice": 149.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/amarula-cream.jpg"
  },
  {
    "id": "amarula-1l",
    "name": "Amarula 1L",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "1L",
    "normalPrice": 215.0,
    "initial": "A1",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "coco-rico-salted-caramel-coconut-cream",
    "name": "Coco Rico Salted Caramel & Coconut Cream",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "CR",
    "specialPrice": 112,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/coco-rico-salted-caramel-coconut-cream.jpg"
  },
  {
    "id": "el-bravo-strawberry",
    "name": "El Bravo Strawberry",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "EBS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "j-germeister",
    "name": "Jägermeister",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 329.99,
    "initial": "JG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "j-germeister-manifest",
    "name": "Jägermeister Manifest",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 449.0,
    "initial": "JGM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "po-10-c",
    "name": "Po-10-C",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "P10C",
    "specialPrice": 155,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/po-10-c.jpg"
  },
  {
    "id": "southern-comfort",
    "name": "Southern Comfort",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "SC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "southern-comfort-lime",
    "name": "Southern Comfort Lime",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 155.0,
    "initial": "SCL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "strawberry-lips-cream-liqueur",
    "name": "Strawberry Lips Cream Liqueur",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 159.99,
    "initial": "SLC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tang-sour-apple",
    "name": "Tang Sour Apple",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 199.99,
    "initial": "TA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tang-sour-blueberry",
    "name": "Tang Sour Blueberry",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 119.99,
    "initial": "TB",
    "specialPrice": 99.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/tang-sour-blueberry.jpg"
  },
  {
    "id": "tant-sannie-se-melktert",
    "name": "Tant Sannie Se Melktert",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 139.99,
    "initial": "TS",
    "specialPrice": 120,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/tant-sannie-se-melktert.jpg"
  },
  {
    "id": "wild-africa-cream",
    "name": "Wild Africa Cream",
    "category": "Cream Liqueurs & Other Liqueurs",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 149.99,
    "initial": "WA",
    "specialPrice": 129.99,
    "specialStart": null,
    "specialEnd": null,
    "image": "specials-images/wild-africa-cream.jpg"
  },
  {
    "id": "mo-t-chandon-brut-imp-rial",
    "name": "Moët & Chandon Brut Impérial",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 649.0,
    "initial": "MTC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "mo-t-chandon-ice-imp-rial",
    "name": "Moët & Chandon Ice Impérial",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 879.0,
    "initial": "MTC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "mo-t-chandon-nectar",
    "name": "Moët & Chandon Nectar",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 799.0,
    "initial": "MTC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "veuve-clicquot-brut",
    "name": "Veuve Clicquot Brut",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 749.99,
    "initial": "VCB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "veuve-clicquot-rich",
    "name": "Veuve Clicquot Rich",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 1049.0,
    "initial": "VCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "veuve-clicquot-ros",
    "name": "Veuve Clicquot Rosé",
    "category": "Champagne / Sparkling Wine",
    "categoryId": "sparkling",
    "emoji": "🍾",
    "size": "750ml",
    "normalPrice": 949.0,
    "initial": "VCR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hennessy",
    "name": "Hennessy",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 580.0,
    "initial": "H",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hennessy-vs",
    "name": "Hennessy VS",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 899.99,
    "initial": "HV",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "martell-vs",
    "name": "Martell VS",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 499.99,
    "initial": "MV",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "r-my-martin-vsop",
    "name": "Rémy Martin VSOP",
    "category": "Cognac",
    "categoryId": "cognac",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 989.99,
    "initial": "RMM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "belgravia-gin-dry-lemon",
    "name": "Belgravia Gin & Dry Lemon",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 129.99,
    "initial": "BG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "brutal-fruit-ruby-apple",
    "name": "Brutal Fruit Ruby Apple",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 125.0,
    "initial": "BFR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "carling-black-label",
    "name": "Carling Black Label",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CBL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-lager",
    "name": "Castle Lager",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 95,
    "initial": "C",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-lite",
    "name": "Castle Lite",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105,
    "initial": "CL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-milk-stout",
    "name": "Castle Milk Stout",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CMS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "flying-fish-pressed-lemon",
    "name": "Flying Fish Pressed Lemon",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 110.0,
    "initial": "FFP",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hunters-dry",
    "name": "Hunters Dry",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "HD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hunters-gold-twister",
    "name": "Hunters Gold Twister",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "HG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "ice-tropez",
    "name": "Ice Tropez",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 275ml NRB",
    "normalPrice": 439.0,
    "initial": "IT",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "lion-lager",
    "name": "Lion Lager",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 85,
    "initial": "LL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "mxd-peach-mojito",
    "name": "MXD Peach Mojito",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 99.99,
    "initial": "MPM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "mxd-pina-colada",
    "name": "MXD Pina Colada",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 99.99,
    "initial": "MPC",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "mxd-watermelon-daiquiri",
    "name": "MXD Watermelon Daiquiri",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 99.99,
    "initial": "MWD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "redd-s-mxd-vodka-guarana",
    "name": "Redd’s MXD Vodka Guarana",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "RSM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "redd-s-mxd-vodka-pine-flavour",
    "name": "Redd’s MXD Vodka Pine Flavour",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "RSM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "windhoek-draught",
    "name": "Windhoek Draught",
    "category": "Six Packs",
    "categoryId": "six-packs",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "WD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-mimosa-orange-spritzer",
    "name": "Robertson Mimosa Orange Spritzer",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 80.0,
    "initial": "MO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "sedgwick-s-the-original-old-brown",
    "name": "Sedgwick's The Original Old Brown",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 54.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  }
];
