window.LBB_CATALOG = [
  {
    "id": "j-b-rare",
    "name": "J&B Rare",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 229.99,
    "initial": "J&B",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jameson",
    "name": "Jameson",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 369.99,
    "initial": "J",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "jack-daniel-s",
    "name": "Jack Daniel's",
    "category": "Whisky",
    "categoryId": "whisky",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 315.0,
    "initial": "JD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "klipdrift-export",
    "name": "Klipdrift Export",
    "category": "Brandy",
    "categoryId": "brandy",
    "emoji": "🥃",
    "size": "750ml",
    "normalPrice": 205.0,
    "initial": "KE",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "red-heart-rum",
    "name": "Red Heart Rum",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 219.99,
    "initial": "RH",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "captain-morgan-spiced-gold",
    "name": "Captain Morgan Spiced Gold",
    "category": "Rum",
    "categoryId": "rum",
    "emoji": "🍹",
    "size": "750ml",
    "normalPrice": 189.99,
    "initial": "CM",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "russian-bear",
    "name": "Russian Bear",
    "category": "Vodka & Gin",
    "categoryId": "vodka-gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "RB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "strettons-original",
    "name": "Strettons Original",
    "category": "Vodka & Gin",
    "categoryId": "vodka-gin",
    "emoji": "🍸",
    "size": "750ml",
    "normalPrice": 179.99,
    "initial": "SO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "wild-africa-cream",
    "name": "Wild Africa Cream",
    "category": "Liqueurs & Cream",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 149.99,
    "initial": "WA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tant-sannie-se-melktert",
    "name": "Tant Sannie Se Melktert",
    "category": "Liqueurs & Cream",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 139.99,
    "initial": "TS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "coco-rico-salted-caramel-coconut-cream",
    "name": "Coco Rico Salted Caramel & Coconut Cream",
    "category": "Liqueurs & Cream",
    "categoryId": "liqueurs",
    "emoji": "🥛",
    "size": "750ml",
    "normalPrice": 129.99,
    "initial": "CR",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "po-10-c",
    "name": "Po-10-C",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 169.99,
    "initial": "P10C",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tang-sour-apple",
    "name": "Tang Sour Apple",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 119.99,
    "initial": "TA",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "tang-sour-blueberry",
    "name": "Tang Sour Blueberry",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 119.99,
    "initial": "TB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "robertson-mimosa-orange-spritzer",
    "name": "Robertson Mimosa Orange Spritzer",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 80.0,
    "initial": "MO",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "sedgwick-s-the-original-old-brown",
    "name": "Sedgwick's The Original Old Brown",
    "category": "Shooters, Flavoured & Fortified Wine",
    "categoryId": "shooters",
    "emoji": "🧪",
    "size": "750ml",
    "normalPrice": 54.0,
    "initial": "OB",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "belgravia-gin-dry-lemon",
    "name": "Belgravia Gin & Dry Lemon",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 129.99,
    "initial": "BG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hunters-dry",
    "name": "Hunters Dry",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "HD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "hunters-gold-twister",
    "name": "Hunters Gold Twister",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 440ml",
    "normalPrice": 115.0,
    "initial": "HG",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-lite",
    "name": "Castle Lite",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "carling-black-label",
    "name": "Carling Black Label",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CBL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-milk-stout",
    "name": "Castle Milk Stout",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "CMS",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "windhoek-draught",
    "name": "Windhoek Draught",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 105.0,
    "initial": "WD",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "castle-lager",
    "name": "Castle Lager",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 95.0,
    "initial": "C",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  },
  {
    "id": "lion-lager",
    "name": "Lion Lager",
    "category": "Beers, Ciders & Premix (6-Packs)",
    "categoryId": "beer",
    "emoji": "🍺",
    "size": "6 × 500ml",
    "normalPrice": 85.0,
    "initial": "LL",
    "specialPrice": null,
    "specialStart": null,
    "specialEnd": null,
    "image": null
  }
];
