(() => {
const catalog=Array.isArray(window.LBB_CATALOG)?window.LBB_CATALOG:[]; const root=document.getElementById("catalogRoot"); if(!root)return;
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",""":"&quot;"}[c]));
const money=n=>`R${Number(n).toFixed(2)}`;
const SA="+02:00"; const parseDate=(v,end=false)=>new Date(`${v}T${end?"23:59:59.999":"00:00:00"}${SA}`);
const c=window.LBB_SPECIALS_CAMPAIGN||{}; const start=parseDate(c.campaignStart), end=parseDate(c.campaignEnd,true); const active=Boolean(c.enabled&&Date.now()>=start&&Date.now()<=end);
const groups=[]; catalog.filter(p=>active&&Number(p.specialPrice)>0&&Number(p.specialPrice)<Number(p.normalPrice)).forEach(p=>{let g=groups.find(x=>x.id===p.categoryId); if(!g){g={id:p.categoryId,name:p.category,emoji:p.emoji,items:[]};groups.push(g)} g.items.push(p)});
root.innerHTML=groups.map(g=>`<section class="category" id="${esc(g.id)}"><div class="category-title"><span aria-hidden="true">${esc(g.emoji)}</span><h3>${esc(g.name)}</h3></div><div class="product-grid specials-product-grid">${g.items.map(p=>{const disc=Math.round((p.normalPrice-p.specialPrice)/p.normalPrice*100); return `<article class="product-card" data-product-id="${esc(p.id)}" data-product-name="${esc(p.name)}" data-category="${esc(p.category)}" data-size="${esc(p.size)}" data-normal-price="${p.normalPrice.toFixed(2)}" data-special-price="${p.specialPrice.toFixed(2)}"><div class="product-placeholder product-media"><img class="product-image" src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.onerror=null;this.closest('.product-media').classList.add('image-error');this.style.display='none';this.closest('.product-media').insertAdjacentHTML('beforeend','<span class="image-error-message">Image failed to load</span>')"></div><div class="product-info"><h4>${esc(p.name)}</h4><p>${esc(p.size)}</p><div class="product-price"><span class="base-price struck">${money(p.normalPrice)}</span><strong class="current-price">${money(p.specialPrice)}</strong></div><div class="special-meta"><span class="special-badge">ON SPECIAL</span><span class="discount-badge">${disc}% OFF</span></div><div class="cart-product-control"><button class="add-to-cart-button" type="button" data-cart-add="${esc(p.id)}"><span class="bottle-plus-icon"><svg viewBox="0 0 24 24"><path class="bottle" d="M9 3h6v4l1 2v11a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V9l1-2V3Z"></path><path class="plus" d="M12 11v6M9 14h6"></path></svg></span><span>Add to Cart</span></button></div></div></article>`}).join('')}</div></section>`).join('');
if(!active||!groups.length){root.innerHTML=''; document.getElementById('noSpecials').hidden=false;}
let t=end.getTime()-Date.now()+1000; if(t>0)setTimeout(()=>location.reload(),Math.min(t,2147483647)); document.addEventListener('visibilitychange',()=>{if(!document.hidden)location.reload()});
})();