(() => {
const root=document.getElementById("catalogRoot"); if(!root)return;
const catalog=Array.isArray(window.LBB_CATALOG)?window.LBB_CATALOG:[];
const q=new URLSearchParams(location.search); const id=q.get("category"); const specials=q.get("specials")==="1";
const c=window.LBB_SPECIALS_CAMPAIGN||{}; const start=new Date(`${c.campaignStart}T00:00:00+02:00`); const end=new Date(`${c.campaignEnd}T23:59:59.999+02:00`); const active=Boolean(c.enabled)&&Date.now()>=start.getTime()&&Date.now()<=end.getTime();
const esc=v=>String(v).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[x]));
const cat=catalog.find(p=>p.categoryId===id); if(!cat)return;
const list=catalog.filter(p=>p.categoryId===id && (!specials || (active&&Number(p.specialPrice)>0&&(p.specialOnly===true||Number(p.specialPrice)<Number(p.normalPrice)))));
const title=document.querySelector(".section-heading h1"), sub=document.querySelector(".section-heading .specials-subtitle"); if(title)title.textContent=cat.category; if(sub)sub.textContent=specials?`Browse current ${cat.category} specials.`:`Browse the full ${cat.category} collection.`;
const money=n=>`R${Number(n).toFixed(2)}`;
root.innerHTML=`<div class="category-return"><a class="category-return-link" href="${specials?"specials.html":"shop.html"}#shop">← Back</a></div><div class="category" id="${esc(id)}"><div class="category-title"><span>${esc(cat.emoji)}</span><h3>${esc(cat.category)}</h3></div><div class="product-grid ${specials?"specials-product-grid":""}">${list.map(p=>`<article class="product-card" data-product-id="${esc(p.id)}" data-product-name="${esc(p.name)}" data-category="${esc(p.category)}" data-size="${esc(p.size)}" data-normal-price="${p.normalPrice.toFixed(2)}" data-special-price="${p.specialPrice||""}" data-special-only="${p.specialOnly===true?"true":"false"}"><div class="product-placeholder product-media">${p.image?`<img class="product-image" src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:`<span class="product-initial">${esc(p.initial)}</span>`}</div><div class="product-info"><h4>${esc(p.name)}</h4><p>${esc(p.size)}</p><div class="product-price">${specials?(p.specialOnly?`<strong class="current-price">${money(p.specialPrice)}</strong>`:`<span class="base-price struck">${money(p.normalPrice)}</span><strong class="current-price">${money(p.specialPrice)}</strong>`):`<strong class="current-price">${money(p.normalPrice)}</strong>`}</div></div></article>`).join("")}</div></div>`;
if(specials&&!active){root.innerHTML=""; const e=document.getElementById("noSpecials"); if(e)e.hidden=false;}
})();